import type { IconType } from 'react-icons'
import {
  LuArrowLeft,
  LuArrowRight,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuCircleCheck,
  LuClock,
  LuDownload,
  LuEraser,
  LuFileDown,
  LuHistory,
  LuMailSearch,
  LuMic,
  LuMicOff,
  LuPencil,
  LuPlay,
  LuPlus,
  LuRefreshCw,
  LuRotateCcw,
  LuSend,
  LuSparkles,
  LuTrash2,
  LuUpload,
  LuWandSparkles,
  LuX,
} from 'react-icons/lu'

/**
 * Single source of truth for the icon of each utility action (FR-010).
 * The same action must always use the same Lucide icon across the app,
 * so add new actions here instead of importing icons ad hoc.
 */
export const ACTION_ICONS = {
  edit: LuPencil,
  delete: LuTrash2,
  sync: LuRefreshCw,
  syncMail: LuMailSearch,
  import: LuUpload,
  export: LuDownload,
  template: LuFileDown,
  prev: LuChevronLeft,
  next: LuChevronRight,
  back: LuArrowLeft,
  regenerate: LuRefreshCw,
  run: LuPlay,
  clear: LuEraser,
  discard: LuX,
  close: LuX,
  send: LuSend,
  mic: LuMic,
  micOff: LuMicOff,
  include: LuCheck,
  exclude: LuX,
  expand: LuChevronDown,
  collapse: LuChevronUp,
  viewAll: LuArrowRight,
  add: LuPlus,
  pay: LuCircleCheck,
  history: LuHistory,
  apply: LuWandSparkles,
  chat: LuSparkles,
  reopen: LuRotateCcw,
  postpone: LuClock,
} satisfies Record<string, IconType>

export type ActionKind = keyof typeof ACTION_ICONS
